(cl:defpackage my_minimal_nodes-srv
  (:use )
  (:export
   "VELOCITYCOMMANDERMSG"
   "<VELOCITYCOMMANDERMSG-REQUEST>"
   "VELOCITYCOMMANDERMSG-REQUEST"
   "<VELOCITYCOMMANDERMSG-RESPONSE>"
   "VELOCITYCOMMANDERMSG-RESPONSE"
  ))

