// Generated by gencpp from file example_ros_service/ExampleServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef EXAMPLE_ROS_SERVICE_MESSAGE_EXAMPLESERVICEMSGREQUEST_H
#define EXAMPLE_ROS_SERVICE_MESSAGE_EXAMPLESERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example_ros_service
{
template <class ContainerAllocator>
struct ExampleServiceMsgRequest_
{
  typedef ExampleServiceMsgRequest_<ContainerAllocator> Type;

  ExampleServiceMsgRequest_()
    : name()  {
    }
  ExampleServiceMsgRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExampleServiceMsgRequest_

typedef ::example_ros_service::ExampleServiceMsgRequest_<std::allocator<void> > ExampleServiceMsgRequest;

typedef boost::shared_ptr< ::example_ros_service::ExampleServiceMsgRequest > ExampleServiceMsgRequestPtr;
typedef boost::shared_ptr< ::example_ros_service::ExampleServiceMsgRequest const> ExampleServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace example_ros_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_ros_service/ExampleServiceMsgRequest";
  }

  static const char* value(const ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
";
  }

  static const char* value(const ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExampleServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_ros_service::ExampleServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_ROS_SERVICE_MESSAGE_EXAMPLESERVICEMSGREQUEST_H
