// Generated by gencpp from file object_finder/objectFinderActionGoal.msg
// DO NOT EDIT!


#ifndef OBJECT_FINDER_MESSAGE_OBJECTFINDERACTIONGOAL_H
#define OBJECT_FINDER_MESSAGE_OBJECTFINDERACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <object_finder/objectFinderGoal.h>

namespace object_finder
{
template <class ContainerAllocator>
struct objectFinderActionGoal_
{
  typedef objectFinderActionGoal_<ContainerAllocator> Type;

  objectFinderActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  objectFinderActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::object_finder::objectFinderGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::object_finder::objectFinderActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_finder::objectFinderActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct objectFinderActionGoal_

typedef ::object_finder::objectFinderActionGoal_<std::allocator<void> > objectFinderActionGoal;

typedef boost::shared_ptr< ::object_finder::objectFinderActionGoal > objectFinderActionGoalPtr;
typedef boost::shared_ptr< ::object_finder::objectFinderActionGoal const> objectFinderActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_finder::objectFinderActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_finder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_finder': ['/home/lrp39/ros_ws/devel/share/object_finder/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'tf': ['/opt/ros/indigo/share/tf/cmake/../msg'], 'pcl_msgs': ['/opt/ros/indigo/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_finder::objectFinderActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_finder::objectFinderActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_finder::objectFinderActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4088afd7d46a8964bad7e3f48c8cd0f0";
  }

  static const char* value(const ::object_finder::objectFinderActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4088afd7d46a8964ULL;
  static const uint64_t static_value2 = 0xbad7e3f48c8cd0f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_finder/objectFinderActionGoal";
  }

  static const char* value(const ::object_finder::objectFinderActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
objectFinderGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: object_finder/objectFinderGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#objectFinder.action\n\
#goal:\n\
#define object codes...add more!\n\
#some generic solid objects:\n\
int32 UPRIGHT_CYLINDER = 1\n\
int32 HORIZONTAL_CYLINDER = 2\n\
int32 CUBE = 3\n\
int32 PRISM = 4\n\
int32 SPHERE = 5\n\
\n\
#some very specific objects...add more!\n\
#better: read these in from a database that is more easily augmented\n\
int32 COKE_CAN_UPRIGHT=100\n\
int32 TOY_BLOCK=101\n\
\n\
#goal fields to fill in:\n\
#identify the object, along with its stable pose type (e.g., upright, horizontal, on faceN)\n\
int32 object_id\n\
#boolean to declare if object is on a horizontal surface of known height:\n\
bool known_surface_ht\n\
#if surface ht is known, fill it in\n\
float32 surface_ht\n\
#optionally, provide dimensions that parameterize generic shapes\n\
#dim1 is a radius (for sphere or cylinder) or length (for cube or prism)\n\
float32 object_dimension1\n\
#dim2 is height (for cylinder or prism)\n\
float32 object_dimension2\n\
#dim3 is width (for prism)\n\
float32 object_dimension3\n\
\n\
";
  }

  static const char* value(const ::object_finder::objectFinderActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objectFinderActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_finder::objectFinderActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_finder::objectFinderActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::object_finder::objectFinderGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_FINDER_MESSAGE_OBJECTFINDERACTIONGOAL_H
