; Auto-generated. Do not edit!


(cl:in-package object_grabber-msg)


;//! \htmlinclude object_grabberResult.msg.html

(cl:defclass <object_grabberResult> (roslisp-msg-protocol:ros-message)
  ((return_code
    :reader return_code
    :initarg :return_code
    :type cl:integer
    :initform 0))
)

(cl:defclass object_grabberResult (<object_grabberResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <object_grabberResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'object_grabberResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name object_grabber-msg:<object_grabberResult> is deprecated: use object_grabber-msg:object_grabberResult instead.")))

(cl:ensure-generic-function 'return_code-val :lambda-list '(m))
(cl:defmethod return_code-val ((m <object_grabberResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader object_grabber-msg:return_code-val is deprecated.  Use object_grabber-msg:return_code instead.")
  (return_code m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<object_grabberResult>)))
    "Constants for message type '<object_grabberResult>"
  '((:SUCCESS . 0)
    (:OBJECT_ACQUIRED . 0)
    (:FAILED_CANNOT_REACH . 1)
    (:FAILED_CANNOT_APPROACH . 2)
    (:FAILED_CANNOT_REACH_GRASP_POSE . 3)
    (:FAILED_CANNOT_REACH_DEPART_POSE . 4)
    (:FAILED_OBJECT_NOT_IN_GRIPPER . 5)
    (:FAILED_OBJECT_UNKNOWN . 6))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'object_grabberResult)))
    "Constants for message type 'object_grabberResult"
  '((:SUCCESS . 0)
    (:OBJECT_ACQUIRED . 0)
    (:FAILED_CANNOT_REACH . 1)
    (:FAILED_CANNOT_APPROACH . 2)
    (:FAILED_CANNOT_REACH_GRASP_POSE . 3)
    (:FAILED_CANNOT_REACH_DEPART_POSE . 4)
    (:FAILED_OBJECT_NOT_IN_GRIPPER . 5)
    (:FAILED_OBJECT_UNKNOWN . 6))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <object_grabberResult>) ostream)
  "Serializes a message object of type '<object_grabberResult>"
  (cl:let* ((signed (cl:slot-value msg 'return_code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <object_grabberResult>) istream)
  "Deserializes a message object of type '<object_grabberResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'return_code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<object_grabberResult>)))
  "Returns string type for a message object of type '<object_grabberResult>"
  "object_grabber/object_grabberResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'object_grabberResult)))
  "Returns string type for a message object of type 'object_grabberResult"
  "object_grabber/object_grabberResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<object_grabberResult>)))
  "Returns md5sum for a message object of type '<object_grabberResult>"
  "36cb571a7713b5757f4b2b6712f127ac")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'object_grabberResult)))
  "Returns md5sum for a message object of type 'object_grabberResult"
  "36cb571a7713b5757f4b2b6712f127ac")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<object_grabberResult>)))
  "Returns full string definition for message of type '<object_grabberResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%#  response codes...~%int32 SUCCESS=0~%int32 OBJECT_ACQUIRED=0~%int32 FAILED_CANNOT_REACH=1~%int32 FAILED_CANNOT_APPROACH=2~%int32 FAILED_CANNOT_REACH_GRASP_POSE=3~%int32 FAILED_CANNOT_REACH_DEPART_POSE=4~%int32 FAILED_OBJECT_NOT_IN_GRIPPER=5~%int32 FAILED_OBJECT_UNKNOWN=6~%int32 return_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'object_grabberResult)))
  "Returns full string definition for message of type 'object_grabberResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%#  response codes...~%int32 SUCCESS=0~%int32 OBJECT_ACQUIRED=0~%int32 FAILED_CANNOT_REACH=1~%int32 FAILED_CANNOT_APPROACH=2~%int32 FAILED_CANNOT_REACH_GRASP_POSE=3~%int32 FAILED_CANNOT_REACH_DEPART_POSE=4~%int32 FAILED_OBJECT_NOT_IN_GRIPPER=5~%int32 FAILED_OBJECT_UNKNOWN=6~%int32 return_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <object_grabberResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <object_grabberResult>))
  "Converts a ROS message object to a list"
  (cl:list 'object_grabberResult
    (cl:cons ':return_code (return_code msg))
))
