// Generated by gencpp from file my_minimal_nodes/VelocityCommanderMsgResponse.msg
// DO NOT EDIT!


#ifndef MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGRESPONSE_H
#define MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_minimal_nodes
{
template <class ContainerAllocator>
struct VelocityCommanderMsgResponse_
{
  typedef VelocityCommanderMsgResponse_<ContainerAllocator> Type;

  VelocityCommanderMsgResponse_()
    : message()  {
    }
  VelocityCommanderMsgResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;




  typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityCommanderMsgResponse_

typedef ::my_minimal_nodes::VelocityCommanderMsgResponse_<std::allocator<void> > VelocityCommanderMsgResponse;

typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgResponse > VelocityCommanderMsgResponsePtr;
typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgResponse const> VelocityCommanderMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_minimal_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_minimal_nodes/VelocityCommanderMsgResponse";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
\n\
\n\
";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityCommanderMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_minimal_nodes::VelocityCommanderMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGRESPONSE_H
