// Generated by gencpp from file my_minimal_nodes/VelocityCommanderMsgRequest.msg
// DO NOT EDIT!


#ifndef MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGREQUEST_H
#define MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace my_minimal_nodes
{
template <class ContainerAllocator>
struct VelocityCommanderMsgRequest_
{
  typedef VelocityCommanderMsgRequest_<ContainerAllocator> Type;

  VelocityCommanderMsgRequest_()
    : amplitude()
    , frequency()  {
    }
  VelocityCommanderMsgRequest_(const ContainerAllocator& _alloc)
    : amplitude(_alloc)
    , frequency(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _amplitude_type;
  _amplitude_type amplitude;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _frequency_type;
  _frequency_type frequency;




  typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityCommanderMsgRequest_

typedef ::my_minimal_nodes::VelocityCommanderMsgRequest_<std::allocator<void> > VelocityCommanderMsgRequest;

typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgRequest > VelocityCommanderMsgRequestPtr;
typedef boost::shared_ptr< ::my_minimal_nodes::VelocityCommanderMsgRequest const> VelocityCommanderMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_minimal_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf538af4db41a58c090f79b647b238d7";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf538af4db41a58cULL;
  static const uint64_t static_value2 = 0x090f79b647b238d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_minimal_nodes/VelocityCommanderMsgRequest";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 amplitude\n\
std_msgs/Float64 frequency\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.amplitude);
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityCommanderMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_minimal_nodes::VelocityCommanderMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "amplitude: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.amplitude);
    s << indent << "frequency: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MINIMAL_NODES_MESSAGE_VELOCITYCOMMANDERMSGREQUEST_H
