(cl:defpackage velocity_action_server-msg
  (:use )
  (:export
   "<VELOCITYACTIONGOAL>"
   "VELOCITYACTIONGOAL"
   "<VELOCITYACTIONRESULT>"
   "VELOCITYACTIONRESULT"
   "<VELOCITYFEEDBACK>"
   "VELOCITYFEEDBACK"
   "<VELOCITYGOAL>"
   "VELOCITYGOAL"
   "<VELOCITYRESULT>"
   "VELOCITYRESULT"
   "<VELOCITYACTION>"
   "VELOCITYACTION"
   "<VELOCITYACTIONFEEDBACK>"
   "VELOCITYACTIONFEEDBACK"
  ))

