; Auto-generated. Do not edit!


(cl:in-package velocity_action_server-msg)


;//! \htmlinclude velocityGoal.msg.html

(cl:defclass <velocityGoal> (roslisp-msg-protocol:ros-message)
  ((amplitude
    :reader amplitude
    :initarg :amplitude
    :type std_msgs-msg:Float64
    :initform (cl:make-instance 'std_msgs-msg:Float64))
   (frequency
    :reader frequency
    :initarg :frequency
    :type std_msgs-msg:Float64
    :initform (cl:make-instance 'std_msgs-msg:Float64))
   (num_cycles
    :reader num_cycles
    :initarg :num_cycles
    :type cl:integer
    :initform 0))
)

(cl:defclass velocityGoal (<velocityGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <velocityGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'velocityGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name velocity_action_server-msg:<velocityGoal> is deprecated: use velocity_action_server-msg:velocityGoal instead.")))

(cl:ensure-generic-function 'amplitude-val :lambda-list '(m))
(cl:defmethod amplitude-val ((m <velocityGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader velocity_action_server-msg:amplitude-val is deprecated.  Use velocity_action_server-msg:amplitude instead.")
  (amplitude m))

(cl:ensure-generic-function 'frequency-val :lambda-list '(m))
(cl:defmethod frequency-val ((m <velocityGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader velocity_action_server-msg:frequency-val is deprecated.  Use velocity_action_server-msg:frequency instead.")
  (frequency m))

(cl:ensure-generic-function 'num_cycles-val :lambda-list '(m))
(cl:defmethod num_cycles-val ((m <velocityGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader velocity_action_server-msg:num_cycles-val is deprecated.  Use velocity_action_server-msg:num_cycles instead.")
  (num_cycles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <velocityGoal>) ostream)
  "Serializes a message object of type '<velocityGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'amplitude) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'frequency) ostream)
  (cl:let* ((signed (cl:slot-value msg 'num_cycles)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <velocityGoal>) istream)
  "Deserializes a message object of type '<velocityGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'amplitude) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'frequency) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num_cycles) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<velocityGoal>)))
  "Returns string type for a message object of type '<velocityGoal>"
  "velocity_action_server/velocityGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'velocityGoal)))
  "Returns string type for a message object of type 'velocityGoal"
  "velocity_action_server/velocityGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<velocityGoal>)))
  "Returns md5sum for a message object of type '<velocityGoal>"
  "ed3e6b67ccca98ffc8c908d8bd51a6cd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'velocityGoal)))
  "Returns md5sum for a message object of type 'velocityGoal"
  "ed3e6b67ccca98ffc8c908d8bd51a6cd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<velocityGoal>)))
  "Returns full string definition for message of type '<velocityGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Float64 amplitude~%std_msgs/Float64 frequency~%int32 num_cycles~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'velocityGoal)))
  "Returns full string definition for message of type 'velocityGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Float64 amplitude~%std_msgs/Float64 frequency~%int32 num_cycles~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <velocityGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'amplitude))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'frequency))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <velocityGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'velocityGoal
    (cl:cons ':amplitude (amplitude msg))
    (cl:cons ':frequency (frequency msg))
    (cl:cons ':num_cycles (num_cycles msg))
))
