; Auto-generated. Do not edit!


(cl:in-package velocity_action_server-msg)


;//! \htmlinclude velocityFeedback.msg.html

(cl:defclass <velocityFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass velocityFeedback (<velocityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <velocityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'velocityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name velocity_action_server-msg:<velocityFeedback> is deprecated: use velocity_action_server-msg:velocityFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <velocityFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader velocity_action_server-msg:feedback-val is deprecated.  Use velocity_action_server-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <velocityFeedback>) ostream)
  "Serializes a message object of type '<velocityFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <velocityFeedback>) istream)
  "Deserializes a message object of type '<velocityFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<velocityFeedback>)))
  "Returns string type for a message object of type '<velocityFeedback>"
  "velocity_action_server/velocityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'velocityFeedback)))
  "Returns string type for a message object of type 'velocityFeedback"
  "velocity_action_server/velocityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<velocityFeedback>)))
  "Returns md5sum for a message object of type '<velocityFeedback>"
  "49ceb5b32ea3af22073ede4a0328249e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'velocityFeedback)))
  "Returns md5sum for a message object of type 'velocityFeedback"
  "49ceb5b32ea3af22073ede4a0328249e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<velocityFeedback>)))
  "Returns full string definition for message of type '<velocityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 feedback ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'velocityFeedback)))
  "Returns full string definition for message of type 'velocityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 feedback ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <velocityFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <velocityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'velocityFeedback
    (cl:cons ':feedback (feedback msg))
))
