; Auto-generated. Do not edit!


(cl:in-package velocity_action_server-msg)


;//! \htmlinclude velocityResult.msg.html

(cl:defclass <velocityResult> (roslisp-msg-protocol:ros-message)
  ((message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass velocityResult (<velocityResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <velocityResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'velocityResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name velocity_action_server-msg:<velocityResult> is deprecated: use velocity_action_server-msg:velocityResult instead.")))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <velocityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader velocity_action_server-msg:message-val is deprecated.  Use velocity_action_server-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <velocityResult>) ostream)
  "Serializes a message object of type '<velocityResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <velocityResult>) istream)
  "Deserializes a message object of type '<velocityResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<velocityResult>)))
  "Returns string type for a message object of type '<velocityResult>"
  "velocity_action_server/velocityResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'velocityResult)))
  "Returns string type for a message object of type 'velocityResult"
  "velocity_action_server/velocityResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<velocityResult>)))
  "Returns md5sum for a message object of type '<velocityResult>"
  "5f003d6bcc824cbd51361d66d8e4f76c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'velocityResult)))
  "Returns md5sum for a message object of type 'velocityResult"
  "5f003d6bcc824cbd51361d66d8e4f76c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<velocityResult>)))
  "Returns full string definition for message of type '<velocityResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'velocityResult)))
  "Returns full string definition for message of type 'velocityResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <velocityResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <velocityResult>))
  "Converts a ROS message object to a list"
  (cl:list 'velocityResult
    (cl:cons ':message (message msg))
))
