// Generated by gencpp from file velocity_action_server/velocityActionGoal.msg
// DO NOT EDIT!


#ifndef VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYACTIONGOAL_H
#define VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <velocity_action_server/velocityGoal.h>

namespace velocity_action_server
{
template <class ContainerAllocator>
struct velocityActionGoal_
{
  typedef velocityActionGoal_<ContainerAllocator> Type;

  velocityActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  velocityActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::velocity_action_server::velocityGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct velocityActionGoal_

typedef ::velocity_action_server::velocityActionGoal_<std::allocator<void> > velocityActionGoal;

typedef boost::shared_ptr< ::velocity_action_server::velocityActionGoal > velocityActionGoalPtr;
typedef boost::shared_ptr< ::velocity_action_server::velocityActionGoal const> velocityActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velocity_action_server::velocityActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velocity_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'velocity_action_server': ['/home/lrp39/ros_ws/devel/share/velocity_action_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f8c8475f3cde52c66327fd3e85daa22";
  }

  static const char* value(const ::velocity_action_server::velocityActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f8c8475f3cde52cULL;
  static const uint64_t static_value2 = 0x66327fd3e85daa22ULL;
};

template<class ContainerAllocator>
struct DataType< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velocity_action_server/velocityActionGoal";
  }

  static const char* value(const ::velocity_action_server::velocityActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
velocityGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: velocity_action_server/velocityGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/Float64 amplitude\n\
std_msgs/Float64 frequency\n\
int32 num_cycles\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::velocity_action_server::velocityActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velocity_action_server::velocityActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velocity_action_server::velocityActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::velocity_action_server::velocityGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYACTIONGOAL_H
