// Generated by gencpp from file velocity_action_server/velocityFeedback.msg
// DO NOT EDIT!


#ifndef VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYFEEDBACK_H
#define VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace velocity_action_server
{
template <class ContainerAllocator>
struct velocityFeedback_
{
  typedef velocityFeedback_<ContainerAllocator> Type;

  velocityFeedback_()
    : feedback(0)  {
    }
  velocityFeedback_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;




  typedef boost::shared_ptr< ::velocity_action_server::velocityFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velocity_action_server::velocityFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct velocityFeedback_

typedef ::velocity_action_server::velocityFeedback_<std::allocator<void> > velocityFeedback;

typedef boost::shared_ptr< ::velocity_action_server::velocityFeedback > velocityFeedbackPtr;
typedef boost::shared_ptr< ::velocity_action_server::velocityFeedback const> velocityFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velocity_action_server::velocityFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velocity_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'velocity_action_server': ['/home/lrp39/ros_ws/devel/share/velocity_action_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ceb5b32ea3af22073ede4a0328249e";
  }

  static const char* value(const ::velocity_action_server::velocityFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ceb5b32ea3af22ULL;
  static const uint64_t static_value2 = 0x073ede4a0328249eULL;
};

template<class ContainerAllocator>
struct DataType< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velocity_action_server/velocityFeedback";
  }

  static const char* value(const ::velocity_action_server::velocityFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 feedback \n\
\n\
";
  }

  static const char* value(const ::velocity_action_server::velocityFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velocity_action_server::velocityFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velocity_action_server::velocityFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYFEEDBACK_H
