// Generated by gencpp from file velocity_action_server/velocityResult.msg
// DO NOT EDIT!


#ifndef VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYRESULT_H
#define VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace velocity_action_server
{
template <class ContainerAllocator>
struct velocityResult_
{
  typedef velocityResult_<ContainerAllocator> Type;

  velocityResult_()
    : message()  {
    }
  velocityResult_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;




  typedef boost::shared_ptr< ::velocity_action_server::velocityResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velocity_action_server::velocityResult_<ContainerAllocator> const> ConstPtr;

}; // struct velocityResult_

typedef ::velocity_action_server::velocityResult_<std::allocator<void> > velocityResult;

typedef boost::shared_ptr< ::velocity_action_server::velocityResult > velocityResultPtr;
typedef boost::shared_ptr< ::velocity_action_server::velocityResult const> velocityResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velocity_action_server::velocityResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velocity_action_server::velocityResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velocity_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'velocity_action_server': ['/home/lrp39/ros_ws/devel/share/velocity_action_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velocity_action_server::velocityResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velocity_action_server::velocityResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velocity_action_server::velocityResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velocity_action_server::velocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::velocity_action_server::velocityResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::velocity_action_server::velocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velocity_action_server/velocityResult";
  }

  static const char* value(const ::velocity_action_server::velocityResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velocity_action_server::velocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string message\n\
";
  }

  static const char* value(const ::velocity_action_server::velocityResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velocity_action_server::velocityResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velocity_action_server::velocityResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velocity_action_server::velocityResult_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELOCITY_ACTION_SERVER_MESSAGE_VELOCITYRESULT_H
